version: "3.1"

services:
  interview-api:
    container_name: interview-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      INTERVIEW_PORT: "3000"
    command: ["yarn", "start"]
    restart: always
